package com.jay.nyxplay.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Playlist interna do NyxPlay — não corresponde a pastas do dispositivo.
 * "Todos os vídeos" é gerada automaticamente pelo scanner.
 * Playlists futuras (Fase 2) serão criadas manualmente pelo utilizador,
 * marcadas com isAutoGenerated = false.
 */
@Entity(tableName = "playlists")
data class PlaylistEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val type: MediaType = MediaType.VIDEO,
    val isAutoGenerated: Boolean = false
)

const val PLAYLIST_TODOS_OS_VIDEOS = "Todos os vídeos"
const val PLAYLIST_TODAS_AS_MUSICAS = "Todas as músicas"
