package com.jay.nyxplay.data

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import kotlinx.coroutines.flow.Flow

@Dao
interface PlaylistDao {

    @Query("SELECT * FROM playlists WHERE name = :name LIMIT 1")
    suspend fun findByName(name: String): PlaylistEntity?

    @Insert
    suspend fun insert(playlist: PlaylistEntity): Long

    @Query("DELETE FROM playlist_media_cross_ref WHERE playlistId = :playlistId")
    suspend fun clearCrossRefs(playlistId: Long)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertCrossRefs(refs: List<PlaylistMediaCrossRef>)

    // --- Playlists manuais (criadas pelo utilizador) ---

    @Query("SELECT * FROM playlists WHERE isAutoGenerated = 0 AND type = :type ORDER BY name")
    fun observeManualPlaylists(type: MediaType): Flow<List<PlaylistEntity>>

    @Query("DELETE FROM playlists WHERE id = :playlistId")
    suspend fun deletePlaylist(playlistId: Long)

    @Query(
        """
        SELECT media_items.* FROM media_items
        INNER JOIN playlist_media_cross_ref ON media_items.uid = playlist_media_cross_ref.mediaUid
        WHERE playlist_media_cross_ref.playlistId = :playlistId
        ORDER BY playlist_media_cross_ref.position ASC
        """
    )
    fun observeMediaForPlaylist(playlistId: Long): Flow<List<MediaEntity>>

    @Query("SELECT COUNT(*) FROM playlist_media_cross_ref WHERE playlistId = :playlistId")
    suspend fun countMediaInPlaylist(playlistId: Long): Int

    @Query("DELETE FROM playlist_media_cross_ref WHERE playlistId = :playlistId AND mediaUid = :mediaUid")
    suspend fun removeMediaFromPlaylist(playlistId: Long, mediaUid: String)

    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insertCrossRef(ref: PlaylistMediaCrossRef)
}
