package com.jay.nyxplay.ui.playlists

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.jay.nyxplay.data.MediaEntity
import com.jay.nyxplay.data.MediaType
import com.jay.nyxplay.data.NyxDatabase
import com.jay.nyxplay.data.PlaylistEntity
import com.jay.nyxplay.data.PlaylistMediaCrossRef
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.launch

class PlaylistViewModel(application: Application) : AndroidViewModel(application) {

    private val db = NyxDatabase.getInstance(application)

    fun observePlaylists(type: MediaType): Flow<List<PlaylistEntity>> =
        db.playlistDao().observeManualPlaylists(type)

    fun observeMediaForPlaylist(playlistId: Long): Flow<List<MediaEntity>> =
        db.playlistDao().observeMediaForPlaylist(playlistId)

    fun createPlaylist(name: String, type: MediaType, onCreated: (Long) -> Unit = {}) {
        if (name.isBlank()) return
        viewModelScope.launch {
            val id = db.playlistDao().insert(
                PlaylistEntity(name = name.trim(), type = type, isAutoGenerated = false)
            )
            onCreated(id)
        }
    }

    fun deletePlaylist(playlistId: Long) {
        viewModelScope.launch { db.playlistDao().deletePlaylist(playlistId) }
    }

    fun addMediaToPlaylist(playlistId: Long, mediaUid: String) {
        viewModelScope.launch {
            val count = db.playlistDao().countMediaInPlaylist(playlistId)
            db.playlistDao().insertCrossRef(PlaylistMediaCrossRef(playlistId, mediaUid, count))
        }
    }

    fun removeMediaFromPlaylist(playlistId: Long, mediaUid: String) {
        viewModelScope.launch { db.playlistDao().removeMediaFromPlaylist(playlistId, mediaUid) }
    }
}
